// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package seo_sitemaps.actions;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;
import seo_sitemaps.proxies.SiteMap;
import seo_sitemaps.proxies.microflows.Microflows;

public class GetSiteMapPaths extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String swagger_json;

	public GetSiteMapPaths(IContext context, java.lang.String swagger_json)
	{
		super(context);
		this.swagger_json = swagger_json;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> list = new ArrayList<IMendixObject>();
		
		String root_url = Microflows.getCanonicalDomain(getContext());
		
		JSONObject jsonObj = new JSONObject(swagger_json);

		String basepath = jsonObj.getString("basePath");
		
		JSONObject array = jsonObj.getJSONObject("paths");
		
		Iterator<String> iterator = array.keys();
		
		String key =null;
		while (iterator.hasNext()) {
            key = (String) iterator.next();

            IMendixObject mxObj = Core.instantiate(this.getContext(), SiteMap.getType());
			
			mxObj.setValue(this.getContext(), SiteMap.MemberNames.Path.toString(), root_url+basepath+key);
			list.add(mxObj);
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetSiteMapPaths";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
