// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package runtime_core.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetConcurrentUsersCount extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Boolean _includeAnonymousUsers;

	public GetConcurrentUsersCount(IContext context, java.lang.Boolean _includeAnonymousUsers)
	{
		super(context);
		this._includeAnonymousUsers = _includeAnonymousUsers;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Core.getConcurrentUserCount(_includeAnonymousUsers);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetConcurrentUsersCount";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
